"""Simulation constants owned by the production 2D battle engine."""

TICK_INTERVAL = 0.1
MAX_TICKS = 1200
FIELD_LENGTH = 36.0
MELEE_RANGE = 1.5
CLOSE_RANGE_PENALTY = 0.5
DEFAULT_ROF_RANGED = 3.0
DEFAULT_ROF_MELEE = 1.5
POP_HOUSE_COST = 5
